module.exports = [
  {
    codAtivo: 1,
    ticker: "MGLU3",
    nome: "Magazine Luiza",
    cotacao: 3.01,
    moeda: "BRL",
  },
  {
    codAtivo: 2,
    ticker: "PETR4",
    nome: "Petrobras",
    cotacao: 29.02,
    moeda: "BRL",
  },
  { codAtivo: 3, ticker: "B3SA3", nome: "B3", cotacao: 11.01, moeda: "BRL" },
  { codAtivo: 4, ticker: "VIIA3", nome: "Via", cotacao: 2.63, moeda: "BRL" },
  { codAtivo: 5, ticker: "CASH3", nome: "Méliuz", cotacao: 1.11, moeda: "BRL" },
  {
    codAtivo: 6,
    ticker: "HAPV3",
    nome: "Hapvida",
    cotacao: 6.09,
    moeda: "BRL",
  },
  {
    codAtivo: 7,
    ticker: "BBDC4",
    nome: "Banco Bradesco",
    cotacao: 17.27,
    moeda: "BRL",
  },
  { codAtivo: 8, ticker: "VALE3", nome: "Vale", cotacao: 68.57, moeda: "BRL" },
  { codAtivo: 9, ticker: "ABEV3", nome: "Ambev", cotacao: 14.56, moeda: "BRL" },
  { codAtivo: 10, ticker: "OIBR3", nome: "Oi", cotacao: 0.5, moeda: "BRL" },
  { codAtivo: 11, ticker: "COGN3", nome: "Cogna", cotacao: 2.3, moeda: "BRL" },
  {
    codAtivo: 12,
    ticker: "ITUB4",
    nome: "Itaú Unibanco",
    cotacao: 23.51,
    moeda: "BRL",
  },
  {
    codAtivo: 13,
    ticker: "PRIO3",
    nome: "PetroRio",
    cotacao: 22.84,
    moeda: "BRL",
  },
  {
    codAtivo: 14,
    ticker: "IRBR3",
    nome: "IRB Brasil RE",
    cotacao: 2.18,
    moeda: "BRL",
  },
  {
    codAtivo: 15,
    ticker: "LWSA3",
    nome: "Locaweb",
    cotacao: 6.69,
    moeda: "BRL",
  },
  {
    codAtivo: 16,
    ticker: "PETR3",
    nome: "Petrobras",
    cotacao: 31.59,
    moeda: "BRL",
  },
  { codAtivo: 17, ticker: "CIEL3", nome: "Cielo", cotacao: 4.12, moeda: "BRL" },
  {
    codAtivo: 18,
    ticker: "ITSA4",
    nome: "Itaúsa",
    cotacao: 8.56,
    moeda: "BRL",
  },
  {
    codAtivo: 19,
    ticker: "RDOR3",
    nome: "Rede D'Or",
    cotacao: 30.53,
    moeda: "BRL",
  },
  { codAtivo: 20, ticker: "WEGE3", nome: "WEG", cotacao: 25.33, moeda: "BRL" },
  {
    codAtivo: 21,
    ticker: "DMMO3",
    nome: "Dommo Energia",
    cotacao: 1.56,
    moeda: "BRL",
  },
  { codAtivo: 22, ticker: "AZUL4", nome: "Azul", cotacao: 12.11, moeda: "BRL" },
  {
    codAtivo: 23,
    ticker: "USIM5",
    nome: "Usiminas",
    cotacao: 9.05,
    moeda: "BRL",
  },
  {
    codAtivo: 24,
    ticker: "GGBR4",
    nome: "Gerdau",
    cotacao: 23.84,
    moeda: "BRL",
  },
  { codAtivo: 25, ticker: "GOLL4", nome: "GOL", cotacao: 8.2, moeda: "BRL" },
  { codAtivo: 26, ticker: "CVCB3", nome: "CVC", cotacao: 7.01, moeda: "BRL" },
  { codAtivo: 27, ticker: "JBSS3", nome: "JBS", cotacao: 30.87, moeda: "BRL" },
  {
    codAtivo: 28,
    ticker: "BBAS3",
    nome: "Banco do Brasil",
    cotacao: 34.91,
    moeda: "BRL",
  },
  {
    codAtivo: 29,
    ticker: "BBDC3",
    nome: "Banco Bradesco",
    cotacao: 14.27,
    moeda: "BRL",
  },
  {
    codAtivo: 30,
    ticker: "MRFG3",
    nome: "Marfrig",
    cotacao: 13.68,
    moeda: "BRL",
  },
  {
    codAtivo: 31,
    ticker: "GOAU4",
    nome: "Metalúrgica Gerdau",
    cotacao: 9.92,
    moeda: "BRL",
  },
  {
    codAtivo: 32,
    ticker: "VBBR3",
    nome: "VBBR3",
    cotacao: 16.98,
    moeda: "BRL",
  },
  {
    codAtivo: 33,
    ticker: "CSNA3",
    nome: "Siderúrgica Nacional",
    cotacao: 14.46,
    moeda: "BRL",
  },
  {
    codAtivo: 34,
    ticker: "GFSA3",
    nome: "Gafisa",
    cotacao: 1.19,
    moeda: "BRL",
  },
  { codAtivo: 35, ticker: "CPLE6", nome: "COPEL", cotacao: 6.85, moeda: "BRL" },
  { codAtivo: 36, ticker: "PETZ3", nome: "Petz", cotacao: 10.28, moeda: "BRL" },
  { codAtivo: 37, ticker: "BRFS3", nome: "BRF", cotacao: 15.36, moeda: "BRL" },
  {
    codAtivo: 38,
    ticker: "MULT3",
    nome: "Multiplan",
    cotacao: 23.74,
    moeda: "BRL",
  },
  {
    codAtivo: 39,
    ticker: "EMBR3",
    nome: "Embraer",
    cotacao: 11.98,
    moeda: "BRL",
  },
  {
    codAtivo: 40,
    ticker: "ESPA3",
    nome: "Espaçolaser",
    cotacao: 2.77,
    moeda: "BRL",
  },
  {
    codAtivo: 41,
    ticker: "CSAN3",
    nome: "Cosan",
    cotacao: 17.77,
    moeda: "BRL",
  },
  {
    codAtivo: 42,
    ticker: "AMER3",
    nome: "AMER3",
    cotacao: 16.93,
    moeda: "BRL",
  },
  {
    codAtivo: 43,
    ticker: "RAIZ4",
    nome: "Raízen",
    cotacao: 4.45,
    moeda: "BRL",
  },
  { codAtivo: 44, ticker: "MRVE3", nome: "MRV", cotacao: 8.95, moeda: "BRL" },
  {
    codAtivo: 45,
    ticker: "ELET3",
    nome: "Eletrobras",
    cotacao: 44.56,
    moeda: "BRL",
  },
  {
    codAtivo: 46,
    ticker: "INEP3",
    nome: "Inepar",
    cotacao: 0.82,
    moeda: "BRL",
  },
  {
    codAtivo: 47,
    ticker: "SUZB3",
    nome: "Suzano",
    cotacao: 45.64,
    moeda: "BRL",
  },
  {
    codAtivo: 48,
    ticker: "CMIG4",
    nome: "CEMIG",
    cotacao: 10.51,
    moeda: "BRL",
  },
  {
    codAtivo: 49,
    ticker: "RENT3",
    nome: "Localiza",
    cotacao: 54.81,
    moeda: "BRL",
  },
  {
    codAtivo: 50,
    ticker: "NTCO3",
    nome: "Natura",
    cotacao: 15.73,
    moeda: "BRL",
  },
  {
    codAtivo: 51,
    ticker: "BPAN4",
    nome: "Banco Pan",
    cotacao: 7.02,
    moeda: "BRL",
  },
  {
    codAtivo: 52,
    ticker: "GMAT3",
    nome: "Grupo Mateus",
    cotacao: 4.2,
    moeda: "BRL",
  },
  {
    codAtivo: 53,
    ticker: "CMIN3",
    nome: "CSN Mineração",
    cotacao: 3.49,
    moeda: "BRL",
  },
  {
    codAtivo: 54,
    ticker: "RRRP3",
    nome: "3R Petroleum",
    cotacao: 30.45,
    moeda: "BRL",
  },
  { codAtivo: 55, ticker: "CBAV3", nome: "CBA", cotacao: 9.81, moeda: "BRL" },
  { codAtivo: 56, ticker: "RAIL3", nome: "Rumo", cotacao: 16.01, moeda: "BRL" },
  {
    codAtivo: 57,
    ticker: "EQTL3",
    nome: "Equatorial Energia",
    cotacao: 23.34,
    moeda: "BRL",
  },
  {
    codAtivo: 58,
    ticker: "LREN3",
    nome: "Lojas Renner",
    cotacao: 24.82,
    moeda: "BRL",
  },
  {
    codAtivo: 59,
    ticker: "TOTS3",
    nome: "Totvs",
    cotacao: 26.37,
    moeda: "BRL",
  },
  {
    codAtivo: 60,
    ticker: "BRML3",
    nome: "BRMalls",
    cotacao: 7.74,
    moeda: "BRL",
  },
  { codAtivo: 61, ticker: "TIMS3", nome: "TIM", cotacao: 12.91, moeda: "BRL" },
  {
    codAtivo: 62,
    ticker: "ASAI3",
    nome: "Assaí",
    cotacao: 15.41,
    moeda: "BRL",
  },
  {
    codAtivo: 63,
    ticker: "SEQL3",
    nome: "Sequoia Logística",
    cotacao: 5.29,
    moeda: "BRL",
  },
  {
    codAtivo: 64,
    ticker: "CYRE3",
    nome: "Cyrela",
    cotacao: 12.34,
    moeda: "BRL",
  },
  {
    codAtivo: 65,
    ticker: "BBSE3",
    nome: "BB Seguridade",
    cotacao: 27.62,
    moeda: "BRL",
  },
  {
    codAtivo: 66,
    ticker: "SOMA3",
    nome: "Grupo Soma",
    cotacao: 10.02,
    moeda: "BRL",
  },
  {
    codAtivo: 67,
    ticker: "CCRO3",
    nome: "Grupo CCR",
    cotacao: 12.25,
    moeda: "BRL",
  },
  {
    codAtivo: 68,
    ticker: "UGPA3",
    nome: "Ultrapar",
    cotacao: 12.68,
    moeda: "BRL",
  },
  {
    codAtivo: 69,
    ticker: "RADL3",
    nome: "RaiaDrogasil",
    cotacao: 19.54,
    moeda: "BRL",
  },
  {
    codAtivo: 70,
    ticker: "ENEV3",
    nome: "Eneva",
    cotacao: 14.53,
    moeda: "BRL",
  },
  {
    codAtivo: 71,
    ticker: "INEP4",
    nome: "Inepar",
    cotacao: 0.79,
    moeda: "BRL",
  },
  { codAtivo: 72, ticker: "CEAB3", nome: "C&A", cotacao: 2.6, moeda: "BRL" },
  {
    codAtivo: 73,
    ticker: "ENJU3",
    nome: "Enjoei",
    cotacao: 1.15,
    moeda: "BRL",
  },
  {
    codAtivo: 74,
    ticker: "AMAR3",
    nome: "Lojas Marisa",
    cotacao: 2.39,
    moeda: "BRL",
  },
  {
    codAtivo: 75,
    ticker: "MOVI3",
    nome: "Movida",
    cotacao: 12.93,
    moeda: "BRL",
  },
  { codAtivo: 76, ticker: "VIVR3", nome: "Viver", cotacao: 0.64, moeda: "BRL" },
  {
    codAtivo: 77,
    ticker: "BEEF3",
    nome: "Minerva",
    cotacao: 13.79,
    moeda: "BRL",
  },
  {
    codAtivo: 78,
    ticker: "KLBN4",
    nome: "Klabin",
    cotacao: 3.64,
    moeda: "BRL",
  },
  {
    codAtivo: 79,
    ticker: "ALPA4",
    nome: "Alpargatas",
    cotacao: 20.71,
    moeda: "BRL",
  },
  {
    codAtivo: 80,
    ticker: "POMO4",
    nome: "Marcopolo",
    cotacao: 2.51,
    moeda: "BRL",
  },
  { codAtivo: 81, ticker: "DXCO3", nome: "Duratex", cotacao: 10, moeda: "BRL" },
  {
    codAtivo: 82,
    ticker: "YDUQ3",
    nome: "YDUQS",
    cotacao: 14.09,
    moeda: "BRL",
  },
  {
    codAtivo: 83,
    ticker: "POSI3",
    nome: "Positivo",
    cotacao: 6.69,
    moeda: "BRL",
  },
  {
    codAtivo: 84,
    ticker: "BRAP4",
    nome: "Bradespar",
    cotacao: 22.43,
    moeda: "BRL",
  },
  {
    codAtivo: 85,
    ticker: "CRFB3",
    nome: "Carrefour Brasil",
    cotacao: 16.83,
    moeda: "BRL",
  },
  {
    codAtivo: 86,
    ticker: "OPCT3",
    nome: "OceanPact",
    cotacao: 1.89,
    moeda: "BRL",
  },
  {
    codAtivo: 87,
    ticker: "HBSA3",
    nome: "Hidrovias do Brasil",
    cotacao: 2.14,
    moeda: "BRL",
  },
  {
    codAtivo: 88,
    ticker: "QUAL3",
    nome: "Qualicorp",
    cotacao: 10.46,
    moeda: "BRL",
  },
  {
    codAtivo: 89,
    ticker: "BRPR3",
    nome: "BR Properties",
    cotacao: 8.39,
    moeda: "BRL",
  },
  {
    codAtivo: 90,
    ticker: "TEND3",
    nome: "Construtora Tenda",
    cotacao: 4.68,
    moeda: "BRL",
  },
  { codAtivo: 91, ticker: "CURY3", nome: "Cury", cotacao: 7.61, moeda: "BRL" },
  {
    codAtivo: 92,
    ticker: "ENBR3",
    nome: "EDP Brasil",
    cotacao: 21.16,
    moeda: "BRL",
  },
  { codAtivo: 93, ticker: "LIGT3", nome: "Light", cotacao: 5.69, moeda: "BRL" },
  {
    codAtivo: 94,
    ticker: "CAML3",
    nome: "Camil Alimentos",
    cotacao: 9.91,
    moeda: "BRL",
  },
  {
    codAtivo: 95,
    ticker: "HYPE3",
    nome: "Hypera",
    cotacao: 39.66,
    moeda: "BRL",
  },
  {
    codAtivo: 96,
    ticker: "SBSP3",
    nome: "Sabesp",
    cotacao: 42.38,
    moeda: "BRL",
  },
  {
    codAtivo: 97,
    ticker: "SMFT3",
    nome: "Smart Fit",
    cotacao: 11.08,
    moeda: "BRL",
  },
  {
    codAtivo: 98,
    ticker: "BKBR3",
    nome: "BK Brasil",
    cotacao: 5.7,
    moeda: "BRL",
  },
  {
    codAtivo: 99,
    ticker: "EZTC3",
    nome: "EZTEC",
    cotacao: 16.23,
    moeda: "BRL",
  },
  {
    codAtivo: 100,
    ticker: "ECOR3",
    nome: "EcoRodovias",
    cotacao: 5.38,
    moeda: "BRL",
  },
  {
    codAtivo: 101,
    ticker: "PCAR3",
    nome: "Grupo Pão de Açúcar",
    cotacao: 17,
    moeda: "BRL",
  },
  {
    codAtivo: 102,
    ticker: "LJQQ3",
    nome: "Lojas Quero-Quero",
    cotacao: 5.71,
    moeda: "BRL",
  },
  {
    codAtivo: 103,
    ticker: "STBP3",
    nome: "Santos Brasil",
    cotacao: 6.22,
    moeda: "BRL",
  },
  {
    codAtivo: 104,
    ticker: "ONCO3",
    nome: "Oncoclínicas",
    cotacao: 5.7,
    moeda: "BRL",
  },
  {
    codAtivo: 105,
    ticker: "RAPT4",
    nome: "Randon",
    cotacao: 10.11,
    moeda: "BRL",
  },
  {
    codAtivo: 106,
    ticker: "MEAL3",
    nome: "IMC Alimentação",
    cotacao: 1.71,
    moeda: "BRL",
  },
  {
    codAtivo: 107,
    ticker: "SIMH3",
    nome: "Simpar",
    cotacao: 9.54,
    moeda: "BRL",
  },
  { codAtivo: 108, ticker: "JHSF3", nome: "JHSF", cotacao: 5.68, moeda: "BRL" },
  {
    codAtivo: 109,
    ticker: "ELET6",
    nome: "Eletrobras",
    cotacao: 45.64,
    moeda: "BRL",
  },
  {
    codAtivo: 110,
    ticker: "AERI3",
    nome: "Aeris",
    cotacao: 2.83,
    moeda: "BRL",
  },
  { codAtivo: 111, ticker: "EVEN3", nome: "Even", cotacao: 4.64, moeda: "BRL" },
  {
    codAtivo: 112,
    ticker: "TRAD3",
    nome: "Traders Club",
    cotacao: 3.93,
    moeda: "BRL",
  },
  {
    codAtivo: 113,
    ticker: "NEOE3",
    nome: "Neoenergia",
    cotacao: 14.47,
    moeda: "BRL",
  },
  {
    codAtivo: 114,
    ticker: "BRSR6",
    nome: "Banrisul",
    cotacao: 9.58,
    moeda: "BRL",
  },
  {
    codAtivo: 115,
    ticker: "SMTO3",
    nome: "São Martinho",
    cotacao: 35.74,
    moeda: "BRL",
  },
  {
    codAtivo: 116,
    ticker: "CLSA3",
    nome: "ClearSale",
    cotacao: 4.5,
    moeda: "BRL",
  },
  {
    codAtivo: 117,
    ticker: "TRIS3",
    nome: "Trisul",
    cotacao: 3.94,
    moeda: "BRL",
  },
  {
    codAtivo: 118,
    ticker: "TRPL4",
    nome: "Transmissão Paulista",
    cotacao: 23.04,
    moeda: "BRL",
  },
  {
    codAtivo: 119,
    ticker: "SAPR4",
    nome: "Sanepar",
    cotacao: 3.6,
    moeda: "BRL",
  },
  {
    codAtivo: 120,
    ticker: "FLRY3",
    nome: "Fleury",
    cotacao: 15.14,
    moeda: "BRL",
  },
  {
    codAtivo: 121,
    ticker: "MLAS3",
    nome: "Multilaser",
    cotacao: 4.79,
    moeda: "BRL",
  },
  {
    codAtivo: 122,
    ticker: "VIVT3",
    nome: "Vivo",
    cotacao: 46.98,
    moeda: "BRL",
  },
  {
    codAtivo: 123,
    ticker: "BRKM5",
    nome: "Braskem",
    cotacao: 34.77,
    moeda: "BRL",
  },
  {
    codAtivo: 124,
    ticker: "LUPA3",
    nome: "Lupatech",
    cotacao: 3.29,
    moeda: "BRL",
  },
  {
    codAtivo: 125,
    ticker: "PSSA3",
    nome: "Porto Seguro",
    cotacao: 18.11,
    moeda: "BRL",
  },
  {
    codAtivo: 126,
    ticker: "MYPK3",
    nome: "Iochpe-Maxion",
    cotacao: 15.52,
    moeda: "BRL",
  },
  {
    codAtivo: 127,
    ticker: "DIRR3",
    nome: "Direcional",
    cotacao: 11.14,
    moeda: "BRL",
  },
  {
    codAtivo: 128,
    ticker: "BOAS3",
    nome: "Boa Vista",
    cotacao: 5.26,
    moeda: "BRL",
  },
  {
    codAtivo: 129,
    ticker: "ANIM3",
    nome: "Ânima Educação",
    cotacao: 4.64,
    moeda: "BRL",
  },
  {
    codAtivo: 130,
    ticker: "CPFE3",
    nome: "CPFL Energia",
    cotacao: 32.17,
    moeda: "BRL",
  },
  {
    codAtivo: 131,
    ticker: "VAMO3",
    nome: "Grupo Vamos",
    cotacao: 11.68,
    moeda: "BRL",
  },
  {
    codAtivo: 132,
    ticker: "EGIE3",
    nome: "ENGIE",
    cotacao: 41.78,
    moeda: "BRL",
  },
  {
    codAtivo: 133,
    ticker: "RECV3",
    nome: "PetroRecôncavo",
    cotacao: 24.1,
    moeda: "BRL",
  },
  {
    codAtivo: 134,
    ticker: "CXSE3",
    nome: "Caixa Seguridade",
    cotacao: 6.91,
    moeda: "BRL",
  },
  { codAtivo: 135, ticker: "JSLG3", nome: "JSL", cotacao: 4.95, moeda: "BRL" },
  {
    codAtivo: 136,
    ticker: "TECN3",
    nome: "Technos",
    cotacao: 2.34,
    moeda: "BRL",
  },
  {
    codAtivo: 137,
    ticker: "NEXP3",
    nome: "NEXP3",
    cotacao: 0.54,
    moeda: "BRL",
  },
  {
    codAtivo: 138,
    ticker: "ENAT3",
    nome: "Enauta",
    cotacao: 16.64,
    moeda: "BRL",
  },
  {
    codAtivo: 139,
    ticker: "SLCE3",
    nome: "SLC Agrícola",
    cotacao: 41.75,
    moeda: "BRL",
  },
  {
    codAtivo: 140,
    ticker: "KLBN3",
    nome: "Klabin",
    cotacao: 3.97,
    moeda: "BRL",
  },
  {
    codAtivo: 141,
    ticker: "NGRD3",
    nome: "Neogrid",
    cotacao: 2.11,
    moeda: "BRL",
  },
  {
    codAtivo: 142,
    ticker: "GRND3",
    nome: "Grendene",
    cotacao: 6.83,
    moeda: "BRL",
  },
  {
    codAtivo: 143,
    ticker: "LAVV3",
    nome: "Lavvi Incorporadora",
    cotacao: 4.72,
    moeda: "BRL",
  },
  {
    codAtivo: 144,
    ticker: "AESB3",
    nome: "AES Brasil",
    cotacao: 10.29,
    moeda: "BRL",
  },
  {
    codAtivo: 145,
    ticker: "SBFG3",
    nome: "Grupo SBF",
    cotacao: 19.9,
    moeda: "BRL",
  },
  {
    codAtivo: 146,
    ticker: "HBOR3",
    nome: "Helbor",
    cotacao: 2.45,
    moeda: "BRL",
  },
  {
    codAtivo: 147,
    ticker: "ARZZ3",
    nome: "Arezzo",
    cotacao: 74.56,
    moeda: "BRL",
  },
  {
    codAtivo: 148,
    ticker: "ALSO3",
    nome: "Aliansce Sonae",
    cotacao: 16.58,
    moeda: "BRL",
  },
  {
    codAtivo: 149,
    ticker: "PTBL3",
    nome: "Portobello",
    cotacao: 7.97,
    moeda: "BRL",
  },
  {
    codAtivo: 150,
    ticker: "CSMG3",
    nome: "COPASA",
    cotacao: 11.48,
    moeda: "BRL",
  },
  {
    codAtivo: 151,
    ticker: "AALR3",
    nome: "Alliar",
    cotacao: 19.99,
    moeda: "BRL",
  },
  {
    codAtivo: 152,
    ticker: "ALPK3",
    nome: "Estapar",
    cotacao: 3.1,
    moeda: "BRL",
  },
  {
    codAtivo: 153,
    ticker: "AMBP3",
    nome: "Ambipar",
    cotacao: 25.81,
    moeda: "BRL",
  },
  {
    codAtivo: 154,
    ticker: "MBLY3",
    nome: "Mobly",
    cotacao: 2.48,
    moeda: "BRL",
  },
  {
    codAtivo: 155,
    ticker: "PGMN3",
    nome: "Pague Menos",
    cotacao: 4.49,
    moeda: "BRL",
  },
  {
    codAtivo: 156,
    ticker: "GUAR3",
    nome: "Guararapes",
    cotacao: 7.7,
    moeda: "BRL",
  },
  {
    codAtivo: 157,
    ticker: "MILS3",
    nome: "Mills",
    cotacao: 6.84,
    moeda: "BRL",
  },
  {
    codAtivo: 158,
    ticker: "SHOW3",
    nome: "Time For Fun",
    cotacao: 2.57,
    moeda: "BRL",
  },
  {
    codAtivo: 159,
    ticker: "MDIA3",
    nome: "M. Dias Branco",
    cotacao: 30.75,
    moeda: "BRL",
  },
  {
    codAtivo: 160,
    ticker: "IFCM3",
    nome: "Infracommerce",
    cotacao: 5.71,
    moeda: "BRL",
  },
  {
    codAtivo: 161,
    ticker: "INTB3",
    nome: "Intelbras",
    cotacao: 26.23,
    moeda: "BRL",
  },
  {
    codAtivo: 162,
    ticker: "JALL3",
    nome: "Jalles Machado",
    cotacao: 7.26,
    moeda: "BRL",
  },
  {
    codAtivo: 163,
    ticker: "BRIT3",
    nome: "Brisanet",
    cotacao: 2.43,
    moeda: "BRL",
  },
  {
    codAtivo: 164,
    ticker: "TPIS3",
    nome: "Triunfo",
    cotacao: 1.25,
    moeda: "BRL",
  },
  {
    codAtivo: 165,
    ticker: "ETER3",
    nome: "Eternit",
    cotacao: 10.67,
    moeda: "BRL",
  },
  {
    codAtivo: 166,
    ticker: "MATD3",
    nome: "Mater Dei",
    cotacao: 8.59,
    moeda: "BRL",
  },
  {
    codAtivo: 167,
    ticker: "RCSL4",
    nome: "Recrusul",
    cotacao: 1.03,
    moeda: "BRL",
  },
  { codAtivo: 168, ticker: "RANI3", nome: "Irani", cotacao: 6.9, moeda: "BRL" },
  {
    codAtivo: 169,
    ticker: "ABCB4",
    nome: "Banco ABC Brasil",
    cotacao: 16.79,
    moeda: "BRL",
  },
  { codAtivo: 170, ticker: "OIBR4", nome: "Oi", cotacao: 1.02, moeda: "BRL" },
  {
    codAtivo: 171,
    ticker: "WIZS3",
    nome: "Wiz Soluções",
    cotacao: 7.6,
    moeda: "BRL",
  },
  {
    codAtivo: 172,
    ticker: "WEST3",
    nome: "Westwing",
    cotacao: 2.25,
    moeda: "BRL",
  },
  {
    codAtivo: 173,
    ticker: "KEPL3",
    nome: "Kepler Weber",
    cotacao: 17.2,
    moeda: "BRL",
  },
  {
    codAtivo: 174,
    ticker: "ORVR3",
    nome: "Orizon",
    cotacao: 26.7,
    moeda: "BRL",
  },
  {
    codAtivo: 175,
    ticker: "AGRO3",
    nome: "BrasilAgro",
    cotacao: 23.99,
    moeda: "BRL",
  },
  {
    codAtivo: 176,
    ticker: "VIVA3",
    nome: "Vivara",
    cotacao: 21.36,
    moeda: "BRL",
  },
  {
    codAtivo: 177,
    ticker: "ROMI3",
    nome: "Indústrias ROMI",
    cotacao: 12.76,
    moeda: "BRL",
  },
  {
    codAtivo: 178,
    ticker: "ODPV3",
    nome: "Odontoprev",
    cotacao: 9.36,
    moeda: "BRL",
  },
  {
    codAtivo: 179,
    ticker: "BLUT3",
    nome: "BLUT3",
    cotacao: 1.01,
    moeda: "BRL",
  },
  {
    codAtivo: 180,
    ticker: "DESK3",
    nome: "Desktop",
    cotacao: 10.04,
    moeda: "BRL",
  },
  {
    codAtivo: 181,
    ticker: "BMGB4",
    nome: "Banco BMG",
    cotacao: 2.46,
    moeda: "BRL",
  },
  { codAtivo: 182, ticker: "TUPY3", nome: "Tupy", cotacao: 22.3, moeda: "BRL" },
  {
    codAtivo: 183,
    ticker: "ITUB3",
    nome: "Itaú Unibanco",
    cotacao: 20.16,
    moeda: "BRL",
  },
  {
    codAtivo: 184,
    ticker: "CPLE3",
    nome: "COPEL",
    cotacao: 6.33,
    moeda: "BRL",
  },
  {
    codAtivo: 185,
    ticker: "ARML3",
    nome: "Armac",
    cotacao: 11.24,
    moeda: "BRL",
  },
  {
    codAtivo: 186,
    ticker: "RNEW4",
    nome: "Renova Energia",
    cotacao: 2.38,
    moeda: "BRL",
  },
  {
    codAtivo: 187,
    ticker: "PNVL3",
    nome: "Dimed",
    cotacao: 10.35,
    moeda: "BRL",
  },
  {
    codAtivo: 188,
    ticker: "SQIA3",
    nome: "Sinqia",
    cotacao: 16.89,
    moeda: "BRL",
  },
  {
    codAtivo: 189,
    ticker: "SEER3",
    nome: "Ser Educacional",
    cotacao: 6.15,
    moeda: "BRL",
  },
  {
    codAtivo: 190,
    ticker: "TTEN3",
    nome: "3tentos",
    cotacao: 8.69,
    moeda: "BRL",
  },
  {
    codAtivo: 191,
    ticker: "PORT3",
    nome: "Wilson Sons",
    cotacao: 8.05,
    moeda: "BRL",
  },
  {
    codAtivo: 192,
    ticker: "VULC3",
    nome: "Vulcabras",
    cotacao: 10.83,
    moeda: "BRL",
  },
  {
    codAtivo: 193,
    ticker: "TASA4",
    nome: "Taurus",
    cotacao: 18.14,
    moeda: "BRL",
  },
  {
    codAtivo: 194,
    ticker: "SAPR3",
    nome: "Sanepar",
    cotacao: 3.44,
    moeda: "BRL",
  },
  {
    codAtivo: 195,
    ticker: "BMOB3",
    nome: "Bemobi",
    cotacao: 12.02,
    moeda: "BRL",
  },
  { codAtivo: 196, ticker: "GGPS3", nome: "GPS", cotacao: 11.56, moeda: "BRL" },
  { codAtivo: 197, ticker: "SYNE3", nome: "SYN", cotacao: 4.1, moeda: "BRL" },
  {
    codAtivo: 198,
    ticker: "BLAU3",
    nome: "Blau Farmacêutica",
    cotacao: 24.79,
    moeda: "BRL",
  },
  {
    codAtivo: 199,
    ticker: "USIM3",
    nome: "Usiminas",
    cotacao: 8.64,
    moeda: "BRL",
  },
  {
    codAtivo: 200,
    ticker: "DASA3",
    nome: "Dasa",
    cotacao: 18.85,
    moeda: "BRL",
  },
  {
    codAtivo: 201,
    ticker: "PDGR3",
    nome: "PDG Realty",
    cotacao: 0.86,
    moeda: "BRL",
  },
  {
    codAtivo: 202,
    ticker: "TFCO4",
    nome: "Track & Field",
    cotacao: 9.56,
    moeda: "BRL",
  },
  {
    codAtivo: 203,
    ticker: "AZEV4",
    nome: "Azevedo & Travassos",
    cotacao: 2.66,
    moeda: "BRL",
  },
  {
    codAtivo: 204,
    ticker: "MTRE3",
    nome: "Mitre Realty",
    cotacao: 4.78,
    moeda: "BRL",
  },
  {
    codAtivo: 205,
    ticker: "PLPL3",
    nome: "Plano&Plano",
    cotacao: 2.48,
    moeda: "BRL",
  },
  {
    codAtivo: 206,
    ticker: "LOGG3",
    nome: "LOG CP",
    cotacao: 19.33,
    moeda: "BRL",
  },
  {
    codAtivo: 207,
    ticker: "FIQE3",
    nome: "Unifique",
    cotacao: 4.16,
    moeda: "BRL",
  },
  { codAtivo: 208, ticker: "BLUT4", nome: "BLUT4", cotacao: 0.5, moeda: "BRL" },
  {
    codAtivo: 209,
    ticker: "MDNE3",
    nome: "Moura Dubeux",
    cotacao: 5.04,
    moeda: "BRL",
  },
  {
    codAtivo: 210,
    ticker: "CMIG3",
    nome: "CEMIG",
    cotacao: 15.91,
    moeda: "BRL",
  },
  {
    codAtivo: 211,
    ticker: "ATMP3",
    nome: "ATMASA",
    cotacao: 1.35,
    moeda: "BRL",
  },
  {
    codAtivo: 212,
    ticker: "CSED3",
    nome: "Cruzeiro do Sul Educacional",
    cotacao: 3.7,
    moeda: "BRL",
  },
  {
    codAtivo: 213,
    ticker: "VLID3",
    nome: "Valid",
    cotacao: 10.04,
    moeda: "BRL",
  },
  {
    codAtivo: 214,
    ticker: "PFRM3",
    nome: "Profarma",
    cotacao: 3.21,
    moeda: "BRL",
  },
  {
    codAtivo: 215,
    ticker: "FHER3",
    nome: "Fertilizantes Heringer",
    cotacao: 18.25,
    moeda: "BRL",
  },
  {
    codAtivo: 216,
    ticker: "FRAS3",
    nome: "Fras-le",
    cotacao: 10.9,
    moeda: "BRL",
  },
  {
    codAtivo: 217,
    ticker: "KRSA3",
    nome: "Kora Saúde",
    cotacao: 3.06,
    moeda: "BRL",
  },
  {
    codAtivo: 218,
    ticker: "LOGN3",
    nome: "Log-In",
    cotacao: 29.95,
    moeda: "BRL",
  },
  { codAtivo: 219, ticker: "IGTI3", nome: "IGTI3", cotacao: 2.4, moeda: "BRL" },
  {
    codAtivo: 220,
    ticker: "SANB4",
    nome: "Banco Santander",
    cotacao: 14.82,
    moeda: "BRL",
  },
  {
    codAtivo: 221,
    ticker: "PARD3",
    nome: "Hermes Pardini",
    cotacao: 19.62,
    moeda: "BRL",
  },
  {
    codAtivo: 222,
    ticker: "PMAM3",
    nome: "Paranapanema",
    cotacao: 7.9,
    moeda: "BRL",
  },
  {
    codAtivo: 223,
    ticker: "NINJ3",
    nome: "GetNinjas",
    cotacao: 2.78,
    moeda: "BRL",
  },
  {
    codAtivo: 224,
    ticker: "LEVE3",
    nome: "Mahle Metal Leve",
    cotacao: 23.87,
    moeda: "BRL",
  },
  { codAtivo: 225, ticker: "PINE4", nome: "PINE", cotacao: 1.09, moeda: "BRL" },
  {
    codAtivo: 226,
    ticker: "LPSB3",
    nome: "Lopes",
    cotacao: 2.85,
    moeda: "BRL",
  },
  {
    codAtivo: 227,
    ticker: "LVTC3",
    nome: "WDC Networks",
    cotacao: 8.36,
    moeda: "BRL",
  },
  {
    codAtivo: 228,
    ticker: "TCSA3",
    nome: "Tecnisa",
    cotacao: 2.33,
    moeda: "BRL",
  },
  {
    codAtivo: 229,
    ticker: "UNIP6",
    nome: "Unipar",
    cotacao: 88.47,
    moeda: "BRL",
  },
  {
    codAtivo: 230,
    ticker: "DEXP3",
    nome: "Dexxos",
    cotacao: 7.51,
    moeda: "BRL",
  },
  {
    codAtivo: 231,
    ticker: "RCSL3",
    nome: "Recrusul",
    cotacao: 3,
    moeda: "BRL",
  },
  {
    codAtivo: 232,
    ticker: "RNEW3",
    nome: "Renova Energia",
    cotacao: 2.58,
    moeda: "BRL",
  },
  {
    codAtivo: 233,
    ticker: "SANB3",
    nome: "Banco Santander",
    cotacao: 13.59,
    moeda: "BRL",
  },
  {
    codAtivo: 234,
    ticker: "CARD3",
    nome: "CSU Cardsystem",
    cotacao: 14.31,
    moeda: "BRL",
  },
  {
    codAtivo: 235,
    ticker: "AGXY3",
    nome: "AgroGalaxy",
    cotacao: 7.41,
    moeda: "BRL",
  },
  {
    codAtivo: 236,
    ticker: "SHUL4",
    nome: "Schulz",
    cotacao: 4.24,
    moeda: "BRL",
  },
  {
    codAtivo: 237,
    ticker: "PDTC3",
    nome: "Padtec",
    cotacao: 3.19,
    moeda: "BRL",
  },
  {
    codAtivo: 238,
    ticker: "FESA4",
    nome: "Ferbasa",
    cotacao: 44.29,
    moeda: "BRL",
  },
  {
    codAtivo: 239,
    ticker: "PRNR3",
    nome: "PRINER",
    cotacao: 5.75,
    moeda: "BRL",
  },
  {
    codAtivo: 240,
    ticker: "GETT3",
    nome: "Getnet",
    cotacao: 2.28,
    moeda: "BRL",
  },
  {
    codAtivo: 241,
    ticker: "ELMD3",
    nome: "Eletromidia",
    cotacao: 10.57,
    moeda: "BRL",
  },
  {
    codAtivo: 242,
    ticker: "JFEN3",
    nome: "João Fortes",
    cotacao: 0.85,
    moeda: "BRL",
  },
  {
    codAtivo: 243,
    ticker: "SOJA3",
    nome: "Boa Safra Sementes",
    cotacao: 10.62,
    moeda: "BRL",
  },
  {
    codAtivo: 244,
    ticker: "MELK3",
    nome: "Melnick",
    cotacao: 3.72,
    moeda: "BRL",
  },
  {
    codAtivo: 245,
    ticker: "ITSA3",
    nome: "Itaúsa",
    cotacao: 9.02,
    moeda: "BRL",
  },
  {
    codAtivo: 246,
    ticker: "RSID3",
    nome: "Rossi Residencial",
    cotacao: 2.56,
    moeda: "BRL",
  },
  {
    codAtivo: 247,
    ticker: "VITT3",
    nome: "Vittia",
    cotacao: 9.48,
    moeda: "BRL",
  },
  {
    codAtivo: 248,
    ticker: "VVEO3",
    nome: "Viveo",
    cotacao: 15.67,
    moeda: "BRL",
  },
  {
    codAtivo: 249,
    ticker: "HBRE3",
    nome: "HBR Realty",
    cotacao: 4.35,
    moeda: "BRL",
  },
  {
    codAtivo: 250,
    ticker: "BPAC5",
    nome: "Banco BTG Pactual",
    cotacao: 5.33,
    moeda: "BRL",
  },
  {
    codAtivo: 251,
    ticker: "DMVF3",
    nome: "D1000 Varejo Farma",
    cotacao: 4.2,
    moeda: "BRL",
  },
  {
    codAtivo: 252,
    ticker: "GETT4",
    nome: "Getnet",
    cotacao: 2.28,
    moeda: "BRL",
  },
  {
    codAtivo: 253,
    ticker: "CTSA4",
    nome: "Santanense",
    cotacao: 0.77,
    moeda: "BRL",
  },
  {
    codAtivo: 254,
    ticker: "TGMA3",
    nome: "Tegma",
    cotacao: 13.61,
    moeda: "BRL",
  },
  {
    codAtivo: 255,
    ticker: "TAEE4",
    nome: "Taesa",
    cotacao: 13.26,
    moeda: "BRL",
  },
  { codAtivo: 256, ticker: "DOTZ3", nome: "Dotz", cotacao: 3.64, moeda: "BRL" },
  {
    codAtivo: 257,
    ticker: "POMO3",
    nome: "Marcopolo",
    cotacao: 2.17,
    moeda: "BRL",
  },
  {
    codAtivo: 258,
    ticker: "CTSA3",
    nome: "Santanense",
    cotacao: 1.55,
    moeda: "BRL",
  },
  {
    codAtivo: 259,
    ticker: "TAEE3",
    nome: "Taesa",
    cotacao: 13.19,
    moeda: "BRL",
  },
  {
    codAtivo: 260,
    ticker: "GOAU3",
    nome: "Metalúrgica Gerdau",
    cotacao: 9.45,
    moeda: "BRL",
  },
  {
    codAtivo: 261,
    ticker: "CAMB3",
    nome: "Cambuci",
    cotacao: 4.49,
    moeda: "BRL",
  },
  {
    codAtivo: 262,
    ticker: "UCAS3",
    nome: "Unicasa",
    cotacao: 2.47,
    moeda: "BRL",
  },
  {
    codAtivo: 263,
    ticker: "GGBR3",
    nome: "Gerdau",
    cotacao: 18.92,
    moeda: "BRL",
  },
  {
    codAtivo: 264,
    ticker: "EUCA4",
    nome: "Eucatex",
    cotacao: 8.28,
    moeda: "BRL",
  },
  {
    codAtivo: 265,
    ticker: "ALLD3",
    nome: "Allied",
    cotacao: 10.21,
    moeda: "BRL",
  },
  {
    codAtivo: 266,
    ticker: "LAND3",
    nome: "Terra Santa",
    cotacao: 26.09,
    moeda: "BRL",
  },
  {
    codAtivo: 267,
    ticker: "BRAP3",
    nome: "Bradespar",
    cotacao: 20.41,
    moeda: "BRL",
  },
  {
    codAtivo: 268,
    ticker: "AZEV3",
    nome: "Azevedo & Travassos",
    cotacao: 3.07,
    moeda: "BRL",
  },
  {
    codAtivo: 269,
    ticker: "OFSA3",
    nome: "Ourofino Saúde Animal",
    cotacao: 21,
    moeda: "BRL",
  },
  {
    codAtivo: 270,
    ticker: "UNIP3",
    nome: "Unipar",
    cotacao: 82.55,
    moeda: "BRL",
  },
  {
    codAtivo: 271,
    ticker: "BOBR4",
    nome: "Bombril",
    cotacao: 1.2,
    moeda: "BRL",
  },
  {
    codAtivo: 272,
    ticker: "PTNT4",
    nome: "Pettenati",
    cotacao: 5.96,
    moeda: "BRL",
  },
  {
    codAtivo: 273,
    ticker: "TCNO4",
    nome: "Tecnosolo",
    cotacao: 1.07,
    moeda: "BRL",
  },
  { codAtivo: 274, ticker: "ATOM3", nome: "ATOM", cotacao: 2.56, moeda: "BRL" },
  {
    codAtivo: 275,
    ticker: "BMEB4",
    nome: "Banco Mercantil do Brasil",
    cotacao: 10.3,
    moeda: "BRL",
  },
  {
    codAtivo: 276,
    ticker: "ENGI4",
    nome: "Energisa",
    cotacao: 6.88,
    moeda: "BRL",
  },
  { codAtivo: 277, ticker: "HAGA4", nome: "Haga", cotacao: 1.18, moeda: "BRL" },
  {
    codAtivo: 278,
    ticker: "CTNM4",
    nome: "Coteminas",
    cotacao: 2.65,
    moeda: "BRL",
  },
  {
    codAtivo: 279,
    ticker: "BEES3",
    nome: "Banestes",
    cotacao: 5.11,
    moeda: "BRL",
  },
  {
    codAtivo: 280,
    ticker: "BPAC3",
    nome: "Banco BTG Pactual",
    cotacao: 12.18,
    moeda: "BRL",
  },
  {
    codAtivo: 281,
    ticker: "TASA3",
    nome: "Taurus",
    cotacao: 18.4,
    moeda: "BRL",
  },
  {
    codAtivo: 282,
    ticker: "MODL4",
    nome: "Banco Modal",
    cotacao: 2.51,
    moeda: "BRL",
  },
  {
    codAtivo: 283,
    ticker: "SULA4",
    nome: "SulAmérica",
    cotacao: 7.35,
    moeda: "BRL",
  },
  {
    codAtivo: 284,
    ticker: "RAPT3",
    nome: "Randon",
    cotacao: 8.73,
    moeda: "BRL",
  },
  {
    codAtivo: 285,
    ticker: "SGPS3",
    nome: "SPRINGS",
    cotacao: 3.45,
    moeda: "BRL",
  },
  {
    codAtivo: 286,
    ticker: "DOHL4",
    nome: "Döhler",
    cotacao: 5.64,
    moeda: "BRL",
  },
  {
    codAtivo: 287,
    ticker: "FRTA3",
    nome: "Pomi Frutas",
    cotacao: 3.82,
    moeda: "BRL",
  },
  {
    codAtivo: 288,
    ticker: "SLED4",
    nome: "Saraiva",
    cotacao: 3.55,
    moeda: "BRL",
  },
  {
    codAtivo: 289,
    ticker: "OSXB3",
    nome: "OSX BRASIL",
    cotacao: 5.24,
    moeda: "BRL",
  },
  {
    codAtivo: 290,
    ticker: "EALT4",
    nome: "Electro Aço Altona",
    cotacao: 6.37,
    moeda: "BRL",
  },
  { codAtivo: 291, ticker: "RDNI3", nome: "RNI", cotacao: 7.3, moeda: "BRL" },
  {
    codAtivo: 292,
    ticker: "TELB3",
    nome: "Telebrás",
    cotacao: 19,
    moeda: "BRL",
  },
  {
    codAtivo: 293,
    ticker: "SULA3",
    nome: "SulAmérica",
    cotacao: 7.57,
    moeda: "BRL",
  },
  {
    codAtivo: 294,
    ticker: "TELB4",
    nome: "Telebrás",
    cotacao: 12.79,
    moeda: "BRL",
  },
  {
    codAtivo: 295,
    ticker: "BAHI3",
    nome: "Bahema",
    cotacao: 10.55,
    moeda: "BRL",
  },
  {
    codAtivo: 296,
    ticker: "RPMG3",
    nome: "Refinaria de Manguinhos",
    cotacao: 2.04,
    moeda: "BRL",
  },
  {
    codAtivo: 297,
    ticker: "MNPR3",
    nome: "Minupar",
    cotacao: 6.4,
    moeda: "BRL",
  },
  {
    codAtivo: 298,
    ticker: "TCNO3",
    nome: "Tecnosolo",
    cotacao: 1.35,
    moeda: "BRL",
  },
  {
    codAtivo: 299,
    ticker: "ENGI3",
    nome: "Energisa",
    cotacao: 12.91,
    moeda: "BRL",
  },
  {
    codAtivo: 300,
    ticker: "COCE5",
    nome: "Coelce",
    cotacao: 45.99,
    moeda: "BRL",
  },
  {
    codAtivo: 301,
    ticker: "CLSC4",
    nome: "CELESC",
    cotacao: 52.8,
    moeda: "BRL",
  },
  {
    codAtivo: 302,
    ticker: "ALUP4",
    nome: "Alupar",
    cotacao: 8.98,
    moeda: "BRL",
  },
  {
    codAtivo: 303,
    ticker: "APER3",
    nome: "Alper",
    cotacao: 27.81,
    moeda: "BRL",
  },
  {
    codAtivo: 304,
    ticker: "MODL3",
    nome: "Banco Modal",
    cotacao: 3.11,
    moeda: "BRL",
  },
  {
    codAtivo: 305,
    ticker: "MWET4",
    nome: "Wetzel",
    cotacao: 9.17,
    moeda: "BRL",
  },
  {
    codAtivo: 306,
    ticker: "ALUP3",
    nome: "Alupar",
    cotacao: 9.05,
    moeda: "BRL",
  },
  {
    codAtivo: 307,
    ticker: "BEES4",
    nome: "Banestes",
    cotacao: 5.37,
    moeda: "BRL",
  },
  {
    codAtivo: 308,
    ticker: "CRPG5",
    nome: "Tronox Pigmentos",
    cotacao: 30.64,
    moeda: "BRL",
  },
  {
    codAtivo: 309,
    ticker: "SNSY5",
    nome: "Sansuy",
    cotacao: 2.95,
    moeda: "BRL",
  },
  { codAtivo: 310, ticker: "CEBR6", nome: "CEB", cotacao: 11.99, moeda: "BRL" },
  { codAtivo: 311, ticker: "HAGA3", nome: "Haga", cotacao: 2.69, moeda: "BRL" },
  {
    codAtivo: 312,
    ticker: "EQPA3",
    nome: "Equatorial Pará",
    cotacao: 4.96,
    moeda: "BRL",
  },
  {
    codAtivo: 313,
    ticker: "TEKA4",
    nome: "Teka",
    cotacao: 15.07,
    moeda: "BRL",
  },
  {
    codAtivo: 314,
    ticker: "MTSA4",
    nome: "METISA",
    cotacao: 37.49,
    moeda: "BRL",
  },
  {
    codAtivo: 315,
    ticker: "PTNT3",
    nome: "Pettenati",
    cotacao: 10.06,
    moeda: "BRL",
  },
  {
    codAtivo: 316,
    ticker: "BRKM3",
    nome: "Braskem",
    cotacao: 35.37,
    moeda: "BRL",
  },
  {
    codAtivo: 317,
    ticker: "RPAD5",
    nome: "Alfa Holdings",
    cotacao: 8.28,
    moeda: "BRL",
  },
  {
    codAtivo: 318,
    ticker: "RSUL4",
    nome: "Metalúrgica Riosulense",
    cotacao: 58.3,
    moeda: "BRL",
  },
  {
    codAtivo: 319,
    ticker: "WHRL4",
    nome: "Whirlpool",
    cotacao: 4.74,
    moeda: "BRL",
  },
  { codAtivo: 320, ticker: "WLMM4", nome: "WLM", cotacao: 20.85, moeda: "BRL" },
  { codAtivo: 321, ticker: "CEBR3", nome: "CEB", cotacao: 14.5, moeda: "BRL" },
  {
    codAtivo: 322,
    ticker: "CTKA4",
    nome: "Karsten",
    cotacao: 10.5,
    moeda: "BRL",
  },
  {
    codAtivo: 323,
    ticker: "MGEL4",
    nome: "Mangels",
    cotacao: 14.65,
    moeda: "BRL",
  },
  {
    codAtivo: 324,
    ticker: "BIOM3",
    nome: "Biomm",
    cotacao: 7.54,
    moeda: "BRL",
  },
  {
    codAtivo: 325,
    ticker: "CGRA4",
    nome: "Grazziotin",
    cotacao: 28.35,
    moeda: "BRL",
  },
  {
    codAtivo: 326,
    ticker: "ALPA3",
    nome: "Alpargatas",
    cotacao: 17,
    moeda: "BRL",
  },
  {
    codAtivo: 327,
    ticker: "EUCA3",
    nome: "Eucatex",
    cotacao: 13,
    moeda: "BRL",
  },
  {
    codAtivo: 328,
    ticker: "BAZA3",
    nome: "Banco da Amazônia",
    cotacao: 40.31,
    moeda: "BRL",
  },
  {
    codAtivo: 329,
    ticker: "WHRL3",
    nome: "Whirlpool",
    cotacao: 4.7,
    moeda: "BRL",
  },
  {
    codAtivo: 330,
    ticker: "TRPL3",
    nome: "Transmissão Paulista",
    cotacao: 29.9,
    moeda: "BRL",
  },
  {
    codAtivo: 331,
    ticker: "CGAS5",
    nome: "Comgás",
    cotacao: 120.2,
    moeda: "BRL",
  },
  {
    codAtivo: 332,
    ticker: "UNIP5",
    nome: "Unipar",
    cotacao: 86.5,
    moeda: "BRL",
  },
  {
    codAtivo: 333,
    ticker: "BRSR3",
    nome: "Banrisul",
    cotacao: 11.45,
    moeda: "BRL",
  },
  {
    codAtivo: 334,
    ticker: "CEDO4",
    nome: "Cedro Têxtil",
    cotacao: 4.63,
    moeda: "BRL",
  },
  {
    codAtivo: 335,
    ticker: "EMAE4",
    nome: "EMAE",
    cotacao: 35.15,
    moeda: "BRL",
  },
  {
    codAtivo: 336,
    ticker: "IGBR3",
    nome: "IGB S/A",
    cotacao: 27.9,
    moeda: "BRL",
  },
  { codAtivo: 337, ticker: "CEED3", nome: "CEEE D", cotacao: 42, moeda: "BRL" },
  {
    codAtivo: 338,
    ticker: "AVLL3",
    nome: "Alphaville",
    cotacao: 19.35,
    moeda: "BRL",
  },
  {
    codAtivo: 339,
    ticker: "CRIV3",
    nome: "Alfa Financeira",
    cotacao: 3.08,
    moeda: "BRL",
  },
  {
    codAtivo: 340,
    ticker: "BAUH4",
    nome: "Excelsior",
    cotacao: 72.94,
    moeda: "BRL",
  },
  {
    codAtivo: 341,
    ticker: "NORD3",
    nome: "Nordon",
    cotacao: 6.3,
    moeda: "BRL",
  },
  {
    codAtivo: 342,
    ticker: "HOOT4",
    nome: "Hotéis Othon",
    cotacao: 1.79,
    moeda: "BRL",
  },
  {
    codAtivo: 343,
    ticker: "SLED3",
    nome: "Saraiva",
    cotacao: 9.18,
    moeda: "BRL",
  },
  { codAtivo: 344, ticker: "DTCY3", nome: "Dtcom", cotacao: 5.5, moeda: "BRL" },
  {
    codAtivo: 345,
    ticker: "ENMT3",
    nome: "Energisa MT",
    cotacao: 81,
    moeda: "BRL",
  },
  {
    codAtivo: 346,
    ticker: "CGRA3",
    nome: "Grazziotin",
    cotacao: 28.19,
    moeda: "BRL",
  },
  {
    codAtivo: 347,
    ticker: "MOAR3",
    nome: "Monteiro Aranha",
    cotacao: 461.5,
    moeda: "BRL",
  },
  {
    codAtivo: 348,
    ticker: "PLAS3",
    nome: "Plascar",
    cotacao: 6.5,
    moeda: "BRL",
  },
  {
    codAtivo: 349,
    ticker: "MNDL3",
    nome: "Mundial",
    cotacao: 24.54,
    moeda: "BRL",
  },
  {
    codAtivo: 350,
    ticker: "SCAR3",
    nome: "São Carlos",
    cotacao: 25.25,
    moeda: "BRL",
  },
  { codAtivo: 351, ticker: "CEBR5", nome: "CEB", cotacao: 12, moeda: "BRL" },
  {
    codAtivo: 352,
    ticker: "REDE3",
    nome: "Rede Energia",
    cotacao: 5.8,
    moeda: "BRL",
  },
  { codAtivo: 353, ticker: "CSRN3", nome: "COSERN", cotacao: 20, moeda: "BRL" },
  {
    codAtivo: 354,
    ticker: "FESA3",
    nome: "Ferbasa",
    cotacao: 45.65,
    moeda: "BRL",
  },
  {
    codAtivo: 355,
    ticker: "LIPR3",
    nome: "Eletropar",
    cotacao: 65.2,
    moeda: "BRL",
  },
  { codAtivo: 356, ticker: "CLSC3", nome: "CELESC", cotacao: 51, moeda: "BRL" },
  {
    codAtivo: 357,
    ticker: "EALT3",
    nome: "Electro Aço Altona",
    cotacao: 8.39,
    moeda: "BRL",
  },
  {
    codAtivo: 358,
    ticker: "DEXP4",
    nome: "Dexxos",
    cotacao: 7.2,
    moeda: "BRL",
  },
  {
    codAtivo: 359,
    ticker: "CRPG6",
    nome: "Tronox Pigmentos",
    cotacao: 30.5,
    moeda: "BRL",
  },
  { codAtivo: 360, ticker: "WLMM3", nome: "WLM", cotacao: 24.9, moeda: "BRL" },
  { codAtivo: 361, ticker: "CSRN5", nome: "COSERN", cotacao: 18, moeda: "BRL" },
  {
    codAtivo: 362,
    ticker: "BMKS3",
    nome: "Monark",
    cotacao: 249.98,
    moeda: "BRL",
  },
  {
    codAtivo: 363,
    ticker: "HETA4",
    nome: "Hercules",
    cotacao: 5.28,
    moeda: "BRL",
  },
  {
    codAtivo: 364,
    ticker: "CALI3",
    nome: "Adolpho Lindenberg",
    cotacao: 9,
    moeda: "BRL",
  },
  {
    codAtivo: 365,
    ticker: "BRGE12",
    nome: "Consórcio Alfa",
    cotacao: 6.37,
    moeda: "BRL",
  },
  {
    codAtivo: 366,
    ticker: "BRGE3",
    nome: "Consórcio Alfa",
    cotacao: 6.22,
    moeda: "BRL",
  },
  {
    codAtivo: 367,
    ticker: "ENMT4",
    nome: "Energisa MT",
    cotacao: 80.99,
    moeda: "BRL",
  },
  {
    codAtivo: 368,
    ticker: "GEPA4",
    nome: "Rio Paranapanema Energia",
    cotacao: 24.52,
    moeda: "BRL",
  },
  {
    codAtivo: 369,
    ticker: "BSLI4",
    nome: "Banco de Brasília",
    cotacao: 15.5,
    moeda: "BRL",
  },
  {
    codAtivo: 370,
    ticker: "BGIP4",
    nome: "Banese",
    cotacao: 18.94,
    moeda: "BRL",
  },
  {
    codAtivo: 371,
    ticker: "CBEE3",
    nome: "Ampla Energia",
    cotacao: 15.72,
    moeda: "BRL",
  },
  {
    codAtivo: 372,
    ticker: "CPLE5",
    nome: "COPEL",
    cotacao: 22.5,
    moeda: "BRL",
  },
  {
    codAtivo: 373,
    ticker: "AFLT3",
    nome: "Afluente T",
    cotacao: 9,
    moeda: "BRL",
  },
  {
    codAtivo: 374,
    ticker: "CSRN6",
    nome: "COSERN",
    cotacao: 17.7,
    moeda: "BRL",
  },
  {
    codAtivo: 375,
    ticker: "CEEB3",
    nome: "COELBA",
    cotacao: 36.7,
    moeda: "BRL",
  },
  {
    codAtivo: 376,
    ticker: "BSLI3",
    nome: "Banco de Brasília",
    cotacao: 21.49,
    moeda: "BRL",
  },
  {
    codAtivo: 377,
    ticker: "BRIV4",
    nome: "Alfa Investimento",
    cotacao: 6.42,
    moeda: "BRL",
  },
  {
    codAtivo: 378,
    ticker: "EQMA3B",
    nome: "Equatorial Maranhão",
    cotacao: 37.06,
    moeda: "BRL",
  },
  {
    codAtivo: 379,
    ticker: "CRIV4",
    nome: "Alfa Financeira",
    cotacao: 4.65,
    moeda: "BRL",
  },
  {
    codAtivo: 380,
    ticker: "MRSA6B",
    nome: "MRS Logística",
    cotacao: 20.5,
    moeda: "BRL",
  },
  {
    codAtivo: 381,
    ticker: "BDLL4",
    nome: "Bardella",
    cotacao: 8.9,
    moeda: "BRL",
  },
  {
    codAtivo: 382,
    ticker: "BALM4",
    nome: "Baumer",
    cotacao: 10.3,
    moeda: "BRL",
  },
  {
    codAtivo: 383,
    ticker: "BRIV3",
    nome: "Alfa Investimento",
    cotacao: 5.58,
    moeda: "BRL",
  },
  {
    codAtivo: 384,
    ticker: "EPAR3",
    nome: "EPAR3",
    cotacao: 11.56,
    moeda: "BRL",
  },
  {
    codAtivo: 385,
    ticker: "JOPA3",
    nome: "Josapar",
    cotacao: 21.6,
    moeda: "BRL",
  },
  {
    codAtivo: 386,
    ticker: "CEPE5",
    nome: "CELPE",
    cotacao: 39.5,
    moeda: "BRL",
  },
  {
    codAtivo: 387,
    ticker: "SNSY3",
    nome: "Sansuy",
    cotacao: 7.39,
    moeda: "BRL",
  },
  {
    codAtivo: 388,
    ticker: "BALM3",
    nome: "Baumer",
    cotacao: 12.9,
    moeda: "BRL",
  },
  {
    codAtivo: 389,
    ticker: "PEAB3",
    nome: "Participações Aliança da Bahia",
    cotacao: 51,
    moeda: "BRL",
  },
  {
    codAtivo: 390,
    ticker: "PATI4",
    nome: "Panatlântica",
    cotacao: 53.98,
    moeda: "BRL",
  },
  {
    codAtivo: 391,
    ticker: "GSHP3",
    nome: "General Shopping & Outlets",
    cotacao: 23.8,
    moeda: "BRL",
  },
  {
    codAtivo: 392,
    ticker: "FNCN3",
    nome: "Finansinos",
    cotacao: 12.71,
    moeda: "BRL",
  },
  {
    codAtivo: 393,
    ticker: "BMEB3",
    nome: "Banco Mercantil do Brasil",
    cotacao: 11.27,
    moeda: "BRL",
  },
  {
    codAtivo: 394,
    ticker: "EKTR4",
    nome: "Elektro",
    cotacao: 29,
    moeda: "BRL",
  },
  {
    codAtivo: 395,
    ticker: "HBTS5",
    nome: "Habitasul",
    cotacao: 30.61,
    moeda: "BRL",
  },
  {
    codAtivo: 396,
    ticker: "CEDO3",
    nome: "Cedro Têxtil",
    cotacao: 6.72,
    moeda: "BRL",
  },
  {
    codAtivo: 397,
    ticker: "LUXM4",
    nome: "Trevisa",
    cotacao: 79.48,
    moeda: "BRL",
  },
  {
    codAtivo: 398,
    ticker: "JOPA4",
    nome: "Josapar",
    cotacao: 35.09,
    moeda: "BRL",
  },
  {
    codAtivo: 399,
    ticker: "PEAB4",
    nome: "Participações Aliança da Bahia",
    cotacao: 88.12,
    moeda: "BRL",
  },
  {
    codAtivo: 400,
    ticker: "BRKM6",
    nome: "Braskem",
    cotacao: 23.9,
    moeda: "BRL",
  },
  {
    codAtivo: 401,
    ticker: "BDLL3",
    nome: "Bardella",
    cotacao: 10.1,
    moeda: "BRL",
  },
  {
    codAtivo: 402,
    ticker: "AHEB6",
    nome: "São Paulo Turismo",
    cotacao: 33,
    moeda: "BRL",
  },
  {
    codAtivo: 403,
    ticker: "RPAD3",
    nome: "Alfa Holdings",
    cotacao: 6.62,
    moeda: "BRL",
  },
  {
    codAtivo: 404,
    ticker: "MERC4",
    nome: "Mercantil do Brasil Financeira",
    cotacao: 8.7,
    moeda: "BRL",
  },
  {
    codAtivo: 405,
    ticker: "BRSR5",
    nome: "Banrisul",
    cotacao: 17.3,
    moeda: "BRL",
  },
  {
    codAtivo: 406,
    ticker: "GEPA3",
    nome: "Rio Paranapanema Energia",
    cotacao: 22.64,
    moeda: "BRL",
  },
  {
    codAtivo: 407,
    ticker: "BMIN4",
    nome: "Banco Mercantil de Investimentos",
    cotacao: 13.57,
    moeda: "BRL",
  },
  {
    codAtivo: 408,
    ticker: "CTNM3",
    nome: "Coteminas",
    cotacao: 7.91,
    moeda: "BRL",
  },
  {
    codAtivo: 409,
    ticker: "EQPA5",
    nome: "Equatorial Pará",
    cotacao: 6.7,
    moeda: "BRL",
  },
  { codAtivo: 410, ticker: "CEEB5", nome: "COELBA", cotacao: 36, moeda: "BRL" },
  {
    codAtivo: 411,
    ticker: "BNBR3",
    nome: "Banco do Nordeste",
    cotacao: 68,
    moeda: "BRL",
  },
  {
    codAtivo: 412,
    ticker: "MRSA5B",
    nome: "MRS Logística",
    cotacao: 25.06,
    moeda: "BRL",
  },
  {
    codAtivo: 413,
    ticker: "SOND5",
    nome: "Sondotécnica",
    cotacao: 43.99,
    moeda: "BRL",
  },
  {
    codAtivo: 414,
    ticker: "GPAR3",
    nome: "CELGPAR",
    cotacao: 28.5,
    moeda: "BRL",
  },
  {
    codAtivo: 415,
    ticker: "BRGE11",
    nome: "Consórcio Alfa",
    cotacao: 6.71,
    moeda: "BRL",
  },
  {
    codAtivo: 416,
    ticker: "MWET3",
    nome: "Wetzel",
    cotacao: 16.05,
    moeda: "BRL",
  },
  {
    codAtivo: 417,
    ticker: "CEPE6",
    nome: "CELPE",
    cotacao: 40.15,
    moeda: "BRL",
  },
  {
    codAtivo: 418,
    ticker: "CGAS3",
    nome: "Comgás",
    cotacao: 119.25,
    moeda: "BRL",
  },
  {
    codAtivo: 419,
    ticker: "LCAM3",
    nome: "Locamerica",
    cotacao: 24.15,
    moeda: "BRL",
  },
  {
    codAtivo: 420,
    ticker: "MRSA3B",
    nome: "MRS Logística",
    cotacao: 28.06,
    moeda: "BRL",
  },
  { codAtivo: 421, ticker: "CRDE3", nome: "CR2", cotacao: 21.57, moeda: "BRL" },
  {
    codAtivo: 422,
    ticker: "RPAD6",
    nome: "Alfa Holdings",
    cotacao: 4.5,
    moeda: "BRL",
  },
  {
    codAtivo: 423,
    ticker: "CSAB4",
    nome: "Cia. de Seg. Aliança da Bahia",
    cotacao: 49.04,
    moeda: "BRL",
  },
  {
    codAtivo: 424,
    ticker: "BMIN3",
    nome: "Banco Mercantil de Investimentos",
    cotacao: 19.76,
    moeda: "BRL",
  },
  {
    codAtivo: 425,
    ticker: "BIDI4",
    nome: "Banco Inter",
    cotacao: 3.41,
    moeda: "BRL",
  },
  {
    codAtivo: 426,
    ticker: "BIDI3",
    nome: "Banco Inter",
    cotacao: 3.4,
    moeda: "BRL",
  },
  {
    codAtivo: 427,
    ticker: "PATI3",
    nome: "Panatlântica",
    cotacao: 69.47,
    moeda: "BRL",
  },
  {
    codAtivo: 428,
    ticker: "CSAB3",
    nome: "Cia. de Seg. Aliança da Bahia",
    cotacao: 50,
    moeda: "BRL",
  },
  {
    codAtivo: 429,
    ticker: "CRPG3",
    nome: "Tronox Pigmentos",
    cotacao: 40.8,
    moeda: "BRL",
  },
  {
    codAtivo: 430,
    ticker: "BRGE8",
    nome: "Consórcio Alfa",
    cotacao: 8.9,
    moeda: "BRL",
  },
  {
    codAtivo: 431,
    ticker: "BGIP3",
    nome: "Banese",
    cotacao: 29.46,
    moeda: "BRL",
  },
  {
    codAtivo: 432,
    ticker: "MTIG4",
    nome: "Metalgráfica Iguaçu",
    cotacao: 40,
    moeda: "BRL",
  },
  {
    codAtivo: 433,
    ticker: "EKTR3",
    nome: "Elektro",
    cotacao: 30,
    moeda: "BRL",
  },
  {
    codAtivo: 434,
    ticker: "MERC3",
    nome: "Mercantil do Brasil Financeira",
    cotacao: 24.1,
    moeda: "BRL",
  },
  {
    codAtivo: 435,
    ticker: "EEEL4",
    nome: "CEEE GT",
    cotacao: 410,
    moeda: "BRL",
  },
  {
    codAtivo: 436,
    ticker: "MAPT4",
    nome: "Cemepe",
    cotacao: 14.17,
    moeda: "BRL",
  },
  {
    codAtivo: 437,
    ticker: "SOND6",
    nome: "Sondotécnica",
    cotacao: 43,
    moeda: "BRL",
  },
  {
    codAtivo: 438,
    ticker: "EEEL3",
    nome: "CEEE GT",
    cotacao: 421.01,
    moeda: "BRL",
  },
  {
    codAtivo: 439,
    ticker: "CEED4",
    nome: "CEEE D",
    cotacao: 65.5,
    moeda: "BRL",
  },
  {
    codAtivo: 440,
    ticker: "USIM6",
    nome: "Usiminas",
    cotacao: 14.5,
    moeda: "BRL",
  },
  {
    codAtivo: 441,
    ticker: "BBRK3",
    nome: "Brasil Brokers",
    cotacao: 0.8,
    moeda: "BRL",
  },
  { codAtivo: 442, ticker: "MTSA3", nome: "METISA", cotacao: 70, moeda: "BRL" },
  {
    codAtivo: 443,
    ticker: "TKNO4",
    nome: "Tekno",
    cotacao: 79.93,
    moeda: "BRL",
  },
  {
    codAtivo: 444,
    ticker: "BRGE6",
    nome: "Consórcio Alfa",
    cotacao: 8.5,
    moeda: "BRL",
  },
  {
    codAtivo: 445,
    ticker: "MSPA4",
    nome: "Melhoramentos",
    cotacao: 46.5,
    moeda: "BRL",
  },
  {
    codAtivo: 446,
    ticker: "SOND3",
    nome: "Sondotécnica",
    cotacao: 46.01,
    moeda: "BRL",
  },
  {
    codAtivo: 447,
    ticker: "CEGR3",
    nome: "Naturgy (CEG)",
    cotacao: 89,
    moeda: "BRL",
  },
  {
    codAtivo: 448,
    ticker: "BRGE5",
    nome: "Consórcio Alfa",
    cotacao: 9.81,
    moeda: "BRL",
  },
  {
    codAtivo: 449,
    ticker: "FRIO3",
    nome: "Metalfrio",
    cotacao: 41.5,
    moeda: "BRL",
  },
  {
    codAtivo: 450,
    ticker: "EQPA7",
    nome: "Equatorial Pará",
    cotacao: 6.62,
    moeda: "BRL",
  },
  {
    codAtivo: 451,
    ticker: "CESP6",
    nome: "CESP",
    cotacao: 25.25,
    moeda: "BRL",
  },
  {
    codAtivo: 452,
    ticker: "CESP3",
    nome: "CESP",
    cotacao: 25.55,
    moeda: "BRL",
  },
  { codAtivo: 453, ticker: "CESP5", nome: "CESP", cotacao: 25, moeda: "BRL" },
  {
    codAtivo: 454,
    ticker: "ECPR4",
    nome: "Encorpar",
    cotacao: 90.74,
    moeda: "BRL",
  },
  {
    codAtivo: 455,
    ticker: "ESTR4",
    nome: "Estrela",
    cotacao: 53,
    moeda: "BRL",
  },
  {
    codAtivo: 456,
    ticker: "MOSI3",
    nome: "Mosaico",
    cotacao: 8.24,
    moeda: "BRL",
  },
  {
    codAtivo: 457,
    ticker: "MSPA3",
    nome: "Melhoramentos",
    cotacao: 50.01,
    moeda: "BRL",
  },
  {
    codAtivo: 458,
    ticker: "POWE3",
    nome: "Focus Energia",
    cotacao: 10.9,
    moeda: "BRL",
  },
  {
    codAtivo: 459,
    ticker: "EQPA6",
    nome: "Equatorial Pará",
    cotacao: 10.69,
    moeda: "BRL",
  },
  {
    codAtivo: 460,
    ticker: "ECPR3",
    nome: "Encorpar",
    cotacao: 90.25,
    moeda: "BRL",
  },
  { codAtivo: 461, ticker: "DOHL3", nome: "Döhler", cotacao: 19, moeda: "BRL" },
  {
    codAtivo: 462,
    ticker: "GNDI3",
    nome: "NotreDame Intermédica",
    cotacao: 65.34,
    moeda: "BRL",
  },
  {
    codAtivo: 463,
    ticker: "CTKA3",
    nome: "Karsten",
    cotacao: 27.5,
    moeda: "BRL",
  },
  { codAtivo: 464, ticker: "TEKA3", nome: "Teka", cotacao: 26.1, moeda: "BRL" },
  {
    codAtivo: 465,
    ticker: "LAME4",
    nome: "Lojas Americanas",
    cotacao: 6.55,
    moeda: "BRL",
  },
  {
    codAtivo: 466,
    ticker: "LAME3",
    nome: "Lojas Americanas",
    cotacao: 6.62,
    moeda: "BRL",
  },
  {
    codAtivo: 467,
    ticker: "AHEB3",
    nome: "São Paulo Turismo",
    cotacao: 27.5,
    moeda: "BRL",
  },
  {
    codAtivo: 468,
    ticker: "AHEB5",
    nome: "São Paulo Turismo",
    cotacao: 22,
    moeda: "BRL",
  },
  {
    codAtivo: 469,
    ticker: "COCE3",
    nome: "Coelce",
    cotacao: 58.92,
    moeda: "BRL",
  },
  {
    codAtivo: 470,
    ticker: "ELET5",
    nome: "Eletrobras",
    cotacao: 64.5,
    moeda: "BRL",
  },
  {
    codAtivo: 471,
    ticker: "OMGE3",
    nome: "Omega Geração",
    cotacao: 27.57,
    moeda: "BRL",
  },
  {
    codAtivo: 472,
    ticker: "IGTA3",
    nome: "Iguatemi",
    cotacao: 33.13,
    moeda: "BRL",
  },
  {
    codAtivo: 473,
    ticker: "JPSA3",
    nome: "Jereissati Participações",
    cotacao: 29.02,
    moeda: "BRL",
  },
  {
    codAtivo: 474,
    ticker: "BRDT3",
    nome: "Vibra Energia",
    cotacao: 22.03,
    moeda: "BRL",
  },
  {
    codAtivo: 475,
    ticker: "JBDU4",
    nome: "Blue Tech Solutions",
    cotacao: 1.36,
    moeda: "BRL",
  },
  {
    codAtivo: 476,
    ticker: "JBDU3",
    nome: "Blue Tech Solutions",
    cotacao: 3.12,
    moeda: "BRL",
  },
  {
    codAtivo: 477,
    ticker: "HGTX3",
    nome: "Hering",
    cotacao: 37.5,
    moeda: "BRL",
  },
  {
    codAtivo: 478,
    ticker: "HETA3",
    nome: "Hercules",
    cotacao: 96,
    moeda: "BRL",
  },
  {
    codAtivo: 479,
    ticker: "CCPR3",
    nome: "CCPR3",
    cotacao: 10.16,
    moeda: "BRL",
  },
  {
    codAtivo: 480,
    ticker: "DTEX3",
    nome: "DTEX3",
    cotacao: 20.63,
    moeda: "BRL",
  },
  {
    codAtivo: 481,
    ticker: "VVAR3",
    nome: "VVAR3",
    cotacao: 11.3,
    moeda: "BRL",
  },
  {
    codAtivo: 482,
    ticker: "CASN3",
    nome: "CASAN",
    cotacao: 15.01,
    moeda: "BRL",
  },
  {
    codAtivo: 483,
    ticker: "PNVL4",
    nome: "Dimed",
    cotacao: 18.62,
    moeda: "BRL",
  },
  {
    codAtivo: 484,
    ticker: "TESA3",
    nome: "Terra Santa",
    cotacao: 48,
    moeda: "BRL",
  },
  {
    codAtivo: 485,
    ticker: "BTOW3",
    nome: "Americanas",
    cotacao: 68,
    moeda: "BRL",
  },
  {
    codAtivo: 486,
    ticker: "ESTR3",
    nome: "Estrela",
    cotacao: 40,
    moeda: "BRL",
  },
  { codAtivo: 487, ticker: "LINX3", nome: "Linx", cotacao: 37.4, moeda: "BRL" },
  {
    codAtivo: 488,
    ticker: "SHUL3",
    nome: "Schulz",
    cotacao: 112.01,
    moeda: "BRL",
  },
  {
    codAtivo: 489,
    ticker: "BTTL3",
    nome: "Embpar",
    cotacao: 19.72,
    moeda: "BRL",
  },
  { codAtivo: 490, ticker: "MAPT3", nome: "Cemepe", cotacao: 37, moeda: "BRL" },
  { codAtivo: 491, ticker: "GPCP3", nome: "GPCP3", cotacao: 49, moeda: "BRL" },
  {
    codAtivo: 492,
    ticker: "GPCP4",
    nome: "GPCP4",
    cotacao: 45.51,
    moeda: "BRL",
  },
  {
    codAtivo: 493,
    ticker: "SMLS3",
    nome: "Smiles",
    cotacao: 22.4,
    moeda: "BRL",
  },
  {
    codAtivo: 494,
    ticker: "MMXM3",
    nome: "MMX Mineração",
    cotacao: 14,
    moeda: "BRL",
  },
  { codAtivo: 495, ticker: "BSEV3", nome: "Biosev", cotacao: 9, moeda: "BRL" },
  {
    codAtivo: 496,
    ticker: "CNTO3",
    nome: "CNTO3",
    cotacao: 28.08,
    moeda: "BRL",
  },
  {
    codAtivo: 497,
    ticker: "TIET4",
    nome: "AES Tietê Energia",
    cotacao: 3.51,
    moeda: "BRL",
  },
  {
    codAtivo: 498,
    ticker: "TIET3",
    nome: "AES Tietê Energia",
    cotacao: 3.49,
    moeda: "BRL",
  },
  {
    codAtivo: 499,
    ticker: "CORR4",
    nome: "Corrêa Ribeiro",
    cotacao: 82,
    moeda: "BRL",
  },
  {
    codAtivo: 500,
    ticker: "ODER4",
    nome: "Conservas Oderich",
    cotacao: 190,
    moeda: "BRL",
  },
  { codAtivo: 501, ticker: "CEPE3", nome: "CELPE", cotacao: 128, moeda: "BRL" },
  {
    codAtivo: 502,
    ticker: "CALI4",
    nome: "Adolpho Lindenberg",
    cotacao: 50,
    moeda: "BRL",
  },
  {
    codAtivo: 503,
    ticker: "SNSY6",
    nome: "Sansuy",
    cotacao: 11.51,
    moeda: "BRL",
  },
  { codAtivo: 504, ticker: "CASN4", nome: "CASAN", cotacao: 10, moeda: "BRL" },
  {
    codAtivo: 505,
    ticker: "EMAE3",
    nome: "EMAE",
    cotacao: 26.01,
    moeda: "BRL",
  },
  {
    codAtivo: 506,
    ticker: "BRGE7",
    nome: "Consórcio Alfa",
    cotacao: 5.4,
    moeda: "BRL",
  },
  {
    codAtivo: 507,
    ticker: "BPAR3",
    nome: "Banpará",
    cotacao: 182.07,
    moeda: "BRL",
  },
  {
    codAtivo: 508,
    ticker: "APTI4",
    nome: "Aliperti",
    cotacao: 3500,
    moeda: "BRL",
  },
  {
    codAtivo: 509,
    ticker: "VSPT3",
    nome: "FCA",
    cotacao: 4999999.5,
    moeda: "BRL",
  },
  {
    codAtivo: 510,
    ticker: "MTIG3",
    nome: "Metalgráfica Iguaçu",
    cotacao: 156.3,
    moeda: "BRL",
  },
  {
    codAtivo: 511,
    ticker: "FIGE4",
    nome: "Investimentos Bemge",
    cotacao: 38.01,
    moeda: "BRL",
  },
  {
    codAtivo: 512,
    ticker: "FIGE3",
    nome: "Investimentos Bemge",
    cotacao: 43,
    moeda: "BRL",
  },
  {
    codAtivo: 513,
    ticker: "LUXM3",
    nome: "Trevisa",
    cotacao: 10,
    moeda: "BRL",
  },
  {
    codAtivo: 514,
    ticker: "TKNO3",
    nome: "Tekno",
    cotacao: 85.7,
    moeda: "BRL",
  },
  { codAtivo: 515, ticker: "COCE6", nome: "Coelce", cotacao: 35, moeda: "BRL" },
  {
    codAtivo: 516,
    ticker: "MGEL3",
    nome: "Mangels",
    cotacao: 75,
    moeda: "BRL",
  },
  {
    codAtivo: 517,
    ticker: "CTSA8",
    nome: "Santanense",
    cotacao: 1,
    moeda: "BRL",
  },
  {
    codAtivo: 518,
    ticker: "MMAQ4",
    nome: "Minasmáquinas",
    cotacao: 200.06,
    moeda: "BRL",
  },
];
